import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AuthContextProvider } from '@/context/AuthContext';
import { AuthGuard } from './components/auth/AuthGuard';
import { Header } from './components/header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Movies',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={inter.className}
                style={{
                    width: '100vw',
                    display: 'flex',
                    flexDirection: 'column',
                    height: '100vh',
                    backgroundColor: '#737373',
                }}
            >
                <AuthContextProvider>
                    <Header />
                    <AuthGuard>{children}</AuthGuard>
                </AuthContextProvider>
            </body>
        </html>
    );
}
